global using WhatsStatusApp.Interfaces;
global using WhatsStatusApp.Models;
global using WhatsStatusApp.Services;
global using WhatsStatusApp.ViewModels;
global using WhatsStatusApp.Views;
global using CommunityToolkit.Mvvm;
global using CommunityToolkit.Mvvm.ComponentModel;
global using System.Windows.Input;
global using OpenGraphNet;